#!/bin/bash

docker run -ti \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`:/workspace \
           -v "$(pwd)/dropins":/opt/eclipse/dropins \
           fgrehm/eclipse:v4.4.1

